/* test_ternary.c - [-1,0,1] packed weights, self-contained, no fixtures.
 *
 * Three claims are checked here, in increasing order of trust:
 *
 *   1. k3_ternary_dequant round-trips the four codes exactly and padding reads as zero
 *      weight. This is a test of the packing, on hand-crafted bytes where the expected
 *      answer is written down rather than generated.
 *
 *   2. k3_ternary_matmul is BIT-IDENTICAL to k3_matmul on the dequantised matrix. The
 *      fp32 path is trusted because it is gated against the torch reference by test_ops;
 *      ternary is not. Comparing bits rather than with a tolerance is what catches a
 *      wrong stride, a dropped tail element or a mis-shifted pair - the same reason
 *      t_matmul_bf16 in test_ops.c compares bits instead of tolerating.
 *
 *   3. The result is right against an fp64 reference within a fixed tolerance, which
 *      guards the (shared) accumulation order itself against a systematic error both
 *      paths could share, and that a code 3 which reaches the kernel poisons the row
 *      with NaN instead of silently reading as a weight.
 *
 * Dimensions are deliberately not multiples of 4 so the packed tail is exercised: the
 * format's last byte holds fewer than four elements, and a kernel that strides the
 * padded width instead of `in` would fail here.
 */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "k3.h"

static int g_pass = 0, g_fail = 0;

/* xorshift, the same generator the benchmarks use, so shapes and seeds can be compared
 * against them by eye. */
static unsigned rng(unsigned *s)
{
    *s ^= *s << 13; *s ^= *s >> 17; *s ^= *s << 5;
    return *s;
}

/* ---- packing helpers, deliberately independent of the engine's ---- */
/* codes[i] in {0,1,2} (code 3 reserved for the poison test). Writes the exact on-disk
 * byte layout the engine documents: 2 bits per element, low pair first. */
static void pack_codes(unsigned char *packed, const unsigned char *codes, int n)
{
    const int pcols = (n + 3) / 4;
    memset(packed, 0, (size_t)pcols);
    for (int i = 0; i < n; i++)
        packed[i / 4] |= (unsigned char)(codes[i] << (2 * (i % 4)));
}

static float code_to_f(unsigned c)
{
    return c == 0 ? 0.0f : c == 1 ? 1.0f : c == 2 ? -1.0f : NAN;
}

/* ------------------------------------------------------------- dequant ---- */
static void t_dequant(void)
{
    /* in = 5: the last byte holds element 4 in its low pair, upper three pairs are pad.
     * Codes written by hand so the expected answer is not generated by the code under
     * test. Row 0 exercises every code including the invalid one; row 1 a zero tail. */
    const int rows = 2, in = 5;
    const unsigned char packed[4] = {
        0x01u | (0x02u << 2) | (0x00u << 4) | (0x01u << 6),   /* +1, -1, 0, +1        */
        0x00u,                                               /* element 4: zero pad  */
        0x02u,                                               /* -1, then zero pad    */
        0x00u,                                               /* elements 2..4: pad   */
    };
    float out[2 * 5];
    const float expect[2][5] = {
        { 1.0f, -1.0f, 0.0f, 1.0f, 0.0f },                   /* pad reads as zero    */
        { -1.0f, 0.0f, 0.0f, 0.0f, 0.0f },
    };

    k3_ternary_dequant(out, packed, rows, in);
    int bad = 0;
    for (int r = 0; r < rows && !bad; r++)
        for (int i = 0; i < in; i++)
            if (out[r * in + i] != expect[r][i]) { bad = 1; break; }
    if (bad) { printf("  FAIL  ternary_dequant codes/pad\n"); g_fail++; }
    else     { printf("  PASS  ternary_dequant codes and zero padding\n"); g_pass++; }

    /* code 3 must surface as NaN, never as a weight. */
    const unsigned char poisoned = 0x03u;
    k3_ternary_dequant(out, &poisoned, 1, 1);
    if (isnan(out[0])) { printf("  PASS  ternary_dequant code 3 poisons as NaN\n"); g_pass++; }
    else { printf("  FAIL  ternary_dequant code 3 read as %g\n", (double)out[0]); g_fail++; }
}

/* ------------------------------------------------------- bit identity ---- */
/* k3_ternary_matmul must equal k3_matmul(_, x, dequantised) bit for bit. The dequantised
 * matrix is built from the codes independently of the engine's LUT, so a wrong LUT entry
 * and a wrong pack are both caught, not just one of them. */
static void t_bitidentical(void)
{
    const int in = 257, out = 129;            /* deliberately not multiples of 4 */
    unsigned char *codes = (unsigned char *)malloc((size_t)in * out);
    unsigned char *packed = (unsigned char *)malloc((size_t)((in + 3) / 4) * out);
    float *Wf = (float *)malloc((size_t)in * out * sizeof(float));
    float *x = (float *)malloc((size_t)in * sizeof(float));
    float *ya = (float *)malloc((size_t)out * sizeof(float));
    float *yb = (float *)malloc((size_t)out * sizeof(float));
    if (!codes || !packed || !Wf || !x || !ya || !yb) {
        printf("  FAIL  ternary_matmul (alloc)\n"); g_fail++; return;
    }

    unsigned s = 0x7E7E1234u;
    for (int i = 0; i < in * out; i++) {
        const unsigned c = rng(&s) % 3u;      /* codes 0,1,2 only; 3 is invalid */
        codes[i] = (unsigned char)c;
        Wf[i] = code_to_f(c);
    }
    for (int r = 0; r < out; r++) pack_codes(packed + (size_t)r * ((in + 3) / 4),
                                             codes + (size_t)r * in, in);
    for (int i = 0; i < in; i++)
        x[i] = (float)(rng(&s) >> 8) / 8388608.0f - 1.0f;

    k3_matmul(ya, x, Wf, in, out);
    k3_ternary_matmul(yb, x, packed, in, out);

    int bad = 0;
    for (int o = 0; o < out; o++) {
        union { float f; unsigned u; } a, b;
        a.f = ya[o]; b.f = yb[o];
        if (a.u != b.u) bad++;
    }
    if (bad) { printf("  FAIL  ternary_matmul  %d/%d rows differ from k3_matmul\n", bad, out); g_fail++; }
    else     { printf("  PASS  ternary_matmul  n=%d   bit-identical to k3_matmul\n", out); g_pass++; }
    free(codes); free(packed); free(Wf); free(x); free(ya); free(yb);
}

/* ---------------------------------------------------------- reference ---- */
/* fp64 reference and the kernel's own double accumulators can differ only by summation
 * order, which stays far below fp32 output precision. The tolerance is real, but loose
 * enough that only a genuinely wrong kernel trips it. */
static void t_reference(void)
{
    const int in = 7168, out = 512;           /* a realistic expert-like shape */
    unsigned char *codes = (unsigned char *)malloc((size_t)in * out);
    unsigned char *packed = (unsigned char *)malloc((size_t)((in + 3) / 4) * out);
    float *x = (float *)malloc((size_t)in * sizeof(float));
    float *y = (float *)malloc((size_t)out * sizeof(float));
    if (!codes || !packed || !x || !y) {
        printf("  FAIL  ternary_matmul reference (alloc)\n"); g_fail++; return;
    }

    unsigned s = 0xA5A5BEEFu;
    for (int i = 0; i < in * out; i++) codes[i] = (unsigned char)(rng(&s) % 3u);
    for (int r = 0; r < out; r++) pack_codes(packed + (size_t)r * ((in + 3) / 4),
                                             codes + (size_t)r * in, in);
    for (int i = 0; i < in; i++)
        x[i] = (float)(rng(&s) >> 8) / 8388608.0f - 1.0f;

    k3_ternary_matmul(y, x, packed, in, out);

    int bad = 0;
    for (int o = 0; o < out && !bad; o++) {
        double ref = 0.0;
        for (int i = 0; i < in; i++)
            ref += (double)code_to_f(codes[(size_t)o * in + i]) * (double)x[i];
        const double tol = 1e-4 + 1e-5 * fabs(ref);
        if (fabs((double)y[o] - ref) > tol) bad = 1;
    }
    if (bad) { printf("  FAIL  ternary_matmul  differs from fp64 reference\n"); g_fail++; }
    else     { printf("  PASS  ternary_matmul  n=%d   within tolerance of fp64 reference\n", out); g_pass++; }
    free(codes); free(packed); free(x); free(y);
}

/* -------------------------------------------------------------- poison ---- */
static void t_poison(void)
{
    const int in = 8, out = 3;
    unsigned char packed[3 * 2];
    float x[8], y[3];
    memset(packed, 0, sizeof packed);
    for (int i = 0; i < in; i++) x[i] = (float)(i + 1);
    packed[2] = 0x03u;                        /* row 1, element 0 is code 3   */
    k3_ternary_matmul(y, x, packed, in, out);
    if (isnan(y[1]) && !isnan(y[0]) && !isnan(y[2])) {
        printf("  PASS  ternary_matmul  code 3 poisons only its row\n"); g_pass++;
    } else {
        printf("  FAIL  ternary_matmul  code 3 did not poison exactly its row\n"); g_fail++;
    }
}

int main(void)
{
    printf("Kimi K3 ternary ops (no fixtures; reference is fp64 and k3_matmul)\n\n");
    t_dequant();
    t_bitidentical();
    t_reference();
    t_poison();
    printf("\n%d passed, %d failed\n", g_pass, g_fail);
    return g_fail ? 1 : 0;
}